services:
  - type: web
    name: financeapp-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm run dev
    envVars:
      - key: PORT
        value: 1337
      - key: MONGO_URL
        value: "mongodb+srv://iratiwari2003:Heramb2010@cluster0.bql0cjk.mongodb.net/your-database-name?retryWrites=true&w=majority&appName=Cluster0"
